version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  db_migrations:
    image: db_migrations
    depends_on:
      - db
    environment:
      ENV: local
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    command: npm run db:migrations
    build: ./api
  api:
    image: api
    depends_on:
      - db_migrations
    environment:
      ENV: local
      APP_PORT: 8080
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - 8080:8080
    build: ./api
  ui:
    image: ui
    ports:
      - 3000:3000
    depends_on:
      - api
    build: ./ui
    tty: true